language: ruby
script: bundle exec rspec
rvm:
  - 2.5.0
  - ruby-head
before_install: gem install bundler -v 1.16.1
matrix:
  allow_failures:
    - rvm: ruby-head
deploy:
  provider: script
  script: sh bin/package_push.sh
  on:
    branch: master